param([ValidateSet("Quick","Formal","All")] [string]$Mode="All")
$ErrorActionPreference="Stop";$Root=$PSScriptRoot;$Results=Join-Path $Root "results";New-Item -ItemType Directory -Force -Path $Results|Out-Null;$Ts=Get-Date -Format "yyyyMMdd_HHmmss";$Master=Join-Path $Results "stage13c_master_$Ts.log"
function Log([string]$m){Write-Host $m;$m|Add-Content -Encoding UTF8 $Master}function Fail([string]$m){Log("ERROR: "+$m);"overall=HOLD`nreason=$m"|Set-Content -Encoding UTF8 (Join-Path $Results "STAGE13C_VALIDATION_latest.txt");throw $m}function RunNative([string]$Exe,[string[]]$A,[string]$L){& $Exe @A *> $L;$rc=$LASTEXITCODE;Get-Content $L|ForEach-Object{Write-Host $_};return $rc}
try{Log "Stage 13C Online/Offline Thin Token H32/H64 v1.0";Log("Mode="+$Mode);& python (Join-Path $Root "preflight_stage13c.py");if($LASTEXITCODE-ne 0){Fail "preflight failed"}
$Candidates=@("D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat","C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat","D:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat","C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat");$Vs=$null;foreach($c in $Candidates){if(Test-Path $c){$Vs=$c;break}};if(-not $Vs){Fail "VS Build Tools 2022 not found"};Log("VS="+$Vs)
$Third=Join-Path $Root "third_party";$Zip=Join-Path $Third "mldsa-native-v2.0.0.zip";$SrcRoot=Join-Path $Third "mldsa-native-2.0.0";if(Test-Path $SrcRoot){Remove-Item -Recurse -Force $SrcRoot};Expand-Archive -Force $Zip $Third;Copy-Item -Force (Join-Path $Root "src\stage13c_lattice_onlineoffline.cpp") (Join-Path $SrcRoot "stage13c_lattice.cpp");Copy-Item -Force (Join-Path $Root "src\stage13c_mldsa_baseline.cpp") (Join-Path $SrcRoot "stage13c_baseline.cpp")
$Orig=Join-Path $SrcRoot "Makefile.Microsoft_nmake";$Mk=Join-Path $SrcRoot "Makefile.STAGE13C";$txt=Get-Content $Orig -Raw;$txt=$txt-replace "CFLAGS = /nologo /O2","CFLAGS = /nologo /O2 /utf-8 /D MLD_CONFIG_NO_RANDOMIZED_API";$extra=@'

stage13c_h32: $(OBJ_FILES_44)
	$(CC) $(CFLAGS) /std:c++17 /EHsc /D MLD_CONFIG_PARAMETER_SET=44 /D STAGE13C_PROFILE_HMAX=32 /c /Fo$(MLDSA44_BUILD_DIR)\stage13c_h32.obj stage13c_lattice.cpp
	@if NOT EXIST $(MLDSA44_BUILD_DIR)\bin mkdir $(MLDSA44_BUILD_DIR)\bin
	$(CC) /nologo /O2 /EHsc /Fe$(MLDSA44_BUILD_DIR)\bin\stage13c_h32.exe $(OBJ_FILES_44) $(MLDSA44_BUILD_DIR)\stage13c_h32.obj /link bcrypt.lib psapi.lib
stage13c_h64: $(OBJ_FILES_44)
	$(CC) $(CFLAGS) /std:c++17 /EHsc /D MLD_CONFIG_PARAMETER_SET=44 /D STAGE13C_PROFILE_HMAX=64 /c /Fo$(MLDSA44_BUILD_DIR)\stage13c_h64.obj stage13c_lattice.cpp
	@if NOT EXIST $(MLDSA44_BUILD_DIR)\bin mkdir $(MLDSA44_BUILD_DIR)\bin
	$(CC) /nologo /O2 /EHsc /Fe$(MLDSA44_BUILD_DIR)\bin\stage13c_h64.exe $(OBJ_FILES_44) $(MLDSA44_BUILD_DIR)\stage13c_h64.obj /link bcrypt.lib psapi.lib
stage13c_baseline: $(OBJ_FILES_44)
	$(CC) $(CFLAGS) /std:c++17 /EHsc /D MLD_CONFIG_PARAMETER_SET=44 /c /Fo$(MLDSA44_BUILD_DIR)\stage13c_baseline.obj stage13c_baseline.cpp
	@if NOT EXIST $(MLDSA44_BUILD_DIR)\bin mkdir $(MLDSA44_BUILD_DIR)\bin
	$(CC) /nologo /O2 /EHsc /Fe$(MLDSA44_BUILD_DIR)\bin\stage13c_baseline.exe $(OBJ_FILES_44) $(MLDSA44_BUILD_DIR)\stage13c_baseline.obj /link bcrypt.lib psapi.lib
'@;Set-Content -Encoding ASCII $Mk ($txt+$extra);$Build=Join-Path $Results "compile_$Ts.cmd";@("@echo off","call `"$Vs`" -arch=x64 -host_arch=x64","cd /d `"$SrcRoot`"","nmake /nologo /f Makefile.STAGE13C stage13c_h32 stage13c_h64 stage13c_baseline","exit /b %errorlevel%")|Set-Content -Encoding ASCII $Build;& cmd.exe /d /c "`"$Build`"" *> (Join-Path $Results "compile_$Ts.log");if($LASTEXITCODE-ne 0){Get-Content (Join-Path $Results "compile_$Ts.log");Fail "compile failed"};Get-Content (Join-Path $Results "compile_$Ts.log")
$Bin=Join-Path $SrcRoot "test\build\mldsa44\bin";$H32=Join-Path $Bin "stage13c_h32.exe";$H64=Join-Path $Bin "stage13c_h64.exe";$Base=Join-Path $Bin "stage13c_baseline.exe";if(!(Test-Path $H32)-or!(Test-Path $H64)-or!(Test-Path $Base)){Fail "exe missing"}
if($Mode-eq"Quick"-or$Mode-eq"All"){Log "QUICK smoke H32/H64/baseline";$Q32=Join-Path $Results "quick_h32_$Ts";$Q64=Join-Path $Results "quick_h64_$Ts";$QB=Join-Path $Results "quick_base_$Ts";New-Item -ItemType Directory -Force $Q32,$Q64,$QB|Out-Null;if((RunNative $H32 @("--quick","--matrix",(Join-Path $Root "config\stage13c_h32_matrix.csv"),"--out",$Q32) (Join-Path $Results "quick_h32_$Ts.log"))-ne 0){Fail "H32 quick"};if((RunNative $H64 @("--quick","--matrix",(Join-Path $Root "config\stage13c_h64_matrix.csv"),"--out",$Q64) (Join-Path $Results "quick_h64_$Ts.log"))-ne 0){Fail "H64 quick"};if((RunNative $Base @("--quick","--matrix",(Join-Path $Root "config\stage13c_baseline_matrix.csv"),"--out",$QB) (Join-Path $Results "quick_base_$Ts.log"))-ne 0){Fail "baseline quick"};Log "QUICK=PASS"}
if($Mode-eq"Formal"-or$Mode-eq"All"){Log "FORMAL H32";$F32=Join-Path $Results "formal_h32_$Ts";New-Item -ItemType Directory -Force $F32|Out-Null;if((RunNative $H32 @("--matrix",(Join-Path $Root "config\stage13c_h32_matrix.csv"),"--out",$F32) (Join-Path $Results "formal_h32_$Ts.log"))-ne 0){Fail "H32 formal"};Log "FORMAL H64";$F64=Join-Path $Results "formal_h64_$Ts";New-Item -ItemType Directory -Force $F64|Out-Null;if((RunNative $H64 @("--matrix",(Join-Path $Root "config\stage13c_h64_matrix.csv"),"--out",$F64) (Join-Path $Results "formal_h64_$Ts.log"))-ne 0){Fail "H64 formal"};Log "FORMAL baselines";$FB=Join-Path $Results "formal_base_$Ts";New-Item -ItemType Directory -Force $FB|Out-Null;if((RunNative $Base @("--matrix",(Join-Path $Root "config\stage13c_baseline_matrix.csv"),"--out",$FB) (Join-Path $Results "formal_base_$Ts.log"))-ne 0){Fail "baseline formal"}
Copy-Item -Force (Join-Path $F32 "stage13c_lattice_online_raw.csv") (Join-Path $Results "stage13c_h32_lattice_raw_latest.csv");Copy-Item -Force (Join-Path $F32 "stage13c_lattice_cold_raw.csv") (Join-Path $Results "stage13c_h32_cold_raw_latest.csv");Copy-Item -Force (Join-Path $F32 "stage13c_lattice_summary.csv") (Join-Path $Results "stage13c_h32_summary_latest.csv");Copy-Item -Force (Join-Path $F32 "STAGE13C_LATTICE_VALIDATION.txt") (Join-Path $Results "STAGE13C_H32_VALIDATION_latest.txt");Copy-Item -Force (Join-Path $F64 "stage13c_lattice_online_raw.csv") (Join-Path $Results "stage13c_h64_lattice_raw_latest.csv");Copy-Item -Force (Join-Path $F64 "stage13c_lattice_cold_raw.csv") (Join-Path $Results "stage13c_h64_cold_raw_latest.csv");Copy-Item -Force (Join-Path $F64 "stage13c_lattice_summary.csv") (Join-Path $Results "stage13c_h64_summary_latest.csv");Copy-Item -Force (Join-Path $F64 "STAGE13C_LATTICE_VALIDATION.txt") (Join-Path $Results "STAGE13C_H64_VALIDATION_latest.txt");Copy-Item -Force (Join-Path $FB "stage13c_mldsa_online_raw.csv") (Join-Path $Results "stage13c_mldsa_online_raw_latest.csv");Copy-Item -Force (Join-Path $FB "stage13c_mldsa_cold_raw.csv") (Join-Path $Results "stage13c_mldsa_cold_raw_latest.csv");Copy-Item -Force (Join-Path $FB "stage13c_mldsa_summary.csv") (Join-Path $Results "stage13c_mldsa_summary_latest.csv");Copy-Item -Force (Join-Path $FB "STAGE13C_MLDSA_VALIDATION.txt") (Join-Path $Results "STAGE13C_MLDSA_VALIDATION_latest.txt");& python (Join-Path $Root "analyze_stage13c.py") $Results;if($LASTEXITCODE-ne 0){Fail "analysis failed"};$files=@("stage13c_h32_lattice_raw_latest.csv","stage13c_h64_lattice_raw_latest.csv","stage13c_mldsa_online_raw_latest.csv");$lines=@();foreach($f in $files){$h=(Get-FileHash -Algorithm SHA256 (Join-Path $Results $f)).Hash.ToLowerInvariant();$lines+=("$f=$h")};$lines|Set-Content -Encoding UTF8 (Join-Path $Results "RAW_ARTIFACT_SHA256_latest.txt");Log "FORMAL=PASS"}
Log "STAGE13C_OVERALL=PASS";Copy-Item -Force $Master (Join-Path $Results "stage13c_master_latest.log");Write-Host "Upload the entire results folder as ZIP.";exit 0}catch{try{Copy-Item -Force $Master (Join-Path $Results "stage13c_master_latest.log") -ErrorAction SilentlyContinue}catch{};Write-Host "Stage 13C stopped. Upload the entire results folder.";exit 20}
